//! T35 的验收测试：比较器与诊断切分（R2 / R3 / R4）。
//!
//! 规则来源全部标注 `testdir_test.go` 的行号：
//! - `checkExpectedOutput`（`:1172-1193`）—— R2
//! - `splitOutput`（`:1195-1213`）—— R3
//! - `wantedErrors`（`:1440-1499`）与 `errorCheck`（`:1249-1304`）—— R4
//! - `replacePrefix`（`:2059-2072`）
//!
//! # 正则的范围（重要）
//!
//! 顶层 `test/` 的 ERROR 模式共 **5435 条**，用到了 `{n,m}` / `[...]` / `+` / `?` / `^` / `$`
//! 等全套 Go 正则 —— 自己实现一套正则引擎不现实（那是另一个项目，且错得很安静）。
//! 而 **E4 冻结的 20 个样本只需要「字面量 + `|` + `.` / `.*` + `\` 转义」**。
//!
//! 所以本模块实现这个**子集**，遇到子集外的构造（`+` `?` `[` `(` `{` `^` `$`）**明确报错**，
//! 由上层判 `harness-failure` —— **绝不静默当成「不匹配」**，那会让 5435 条里的绝大多数
//! 用例被误判为「编译器有 bug」。
//!
//! TDD 位置：**RED**。T35 实现前本文件编译不过（`rgoc_harness::compare` 尚不存在）。

use rgoc_harness::compare::{
    OutputMismatch, check_expected_output, error_check, replace_prefix, split_output,
    unanchored_match, wanted_errors,
};

// ══ R2：输出期望（`:1172-1193`）════════════════════════════════════════════

#[test]
fn r2_有_out_且内容相同() {
    assert!(check_expected_output("hello, world\n", Some("hello, world\n")).is_ok());
}

#[test]
fn r2_换行符归一() {
    // :1184 —— 比较前把 \r\n 归一为 \n
    assert!(
        check_expected_output("a\r\nb\n", Some("a\nb\n")).is_ok(),
        "\\r\\n 应当被归一成 \\n 再比"
    );
}

#[test]
fn r2_严格相等_多一个换行也不行() {
    // :1185 是**严格相等**，不是「包含」
    assert!(check_expected_output("hello\n", Some("hello")).is_err());
    assert!(check_expected_output("hello world\n", Some("hello\n")).is_err());
}

#[test]
fn r2_缺_out_即期望为空() {
    // :1178-1182 —— 文件不存在时 b = nil，**不是「任意输出都通过」**
    assert!(
        check_expected_output("", None).is_ok(),
        "缺 .out 且输出为空 ⇒ 通过"
    );
    let e = check_expected_output("boom\n", None).unwrap_err();
    assert!(
        e.to_string().contains("本应为空"),
        "缺 .out 时的措辞应是「本应为空却非空」，实际：{e}"
    );
}

#[test]
fn r2_两种不匹配的措辞不同() {
    // :1186-1190 —— 有 .out 说「内容不符」，无 .out 说「本应为空」
    let with = check_expected_output("x\n", Some("y\n")).unwrap_err();
    assert!(
        with.to_string().contains("不匹配"),
        "有 .out 时的措辞：{with}"
    );
    let without = check_expected_output("x\n", None).unwrap_err();
    assert!(
        without.to_string().contains("本应为空"),
        "无 .out 时的措辞：{without}"
    );
    // 两种措辞必须能区分开（官方就是靠这个告诉人「是输出错了」还是「本该静默」）
    assert_ne!(with.to_string(), without.to_string());
}

#[test]
fn r2_不匹配时_报出实际看到的() {
    let e: OutputMismatch = check_expected_output("a\nb\n", Some("a\n")).unwrap_err();
    assert!(e.to_string().contains('a'), "错误里应能看到实际输出：{e}");
}

// ══ R3：诊断切分（`:1195-1213`）═══════════════════════════════════════════

#[test]
fn r3_制表符开头_续行拼到上一条() {
    let out = "a.go:3:2: first problem\n\tb.go:4:1: detail one\n\tb.go:5:1: detail two\n";
    let got = split_output(out, false);
    assert_eq!(got.len(), 1, "续行应拼进同一条：{got:?}");
    assert_eq!(got[0].lines().count(), 3, "拼进去后是 3 行");
    assert!(got[0].contains("detail one") && got[0].contains("detail two"));
}

#[test]
fn r3_跳过_go_tool_井号_与_autogenerated() {
    // :1206 —— 以 "go tool" / "#" / "<autogenerated>" 开头的行跳过
    let out = "# command-line-arguments\ngo tool compile -V=full\nx.go:1:1: real\n";
    assert_eq!(split_output(out, false), vec!["x.go:1:1: real".to_string()]);
    // wantAuto 为真时 <autogenerated> **不**跳过（GC_ERRORAUTO 用它）
    let out2 = "<autogenerated>:1:1: from autogenerated\nx.go:1:1: real\n";
    assert_eq!(
        split_output(out2, true).len(),
        2,
        "want_auto 时要保留 autogenerated 行"
    );
    assert_eq!(
        split_output(out2, false).len(),
        1,
        "默认丢掉 autogenerated 行"
    );
}

#[test]
fn r3_跳过纯空白行() {
    // :1208
    // 只用空格与空行 —— 单独一个 "\t" 行在官方语义里是**续行**，会拼进上一条
    let out = "a.go:1:1: one\n   \n\nb.go:2:1: two\n";
    assert_eq!(
        split_output(out, false),
        vec!["a.go:1:1: one".to_string(), "b.go:2:1: two".to_string()]
    );
}

#[test]
fn r3_去掉行尾_cr() {
    // :1201-1202 —— 兼容 Windows 上编译器的 \r
    assert_eq!(
        split_output("a.go:1:1: one\r\n", false),
        vec!["a.go:1:1: one".to_string()]
    );
}

// ══ R4：ERROR 注释解析（`:1440-1499`）══════════════════════════════════════

#[test]
fn r4_基本_error_注释() {
    let src = "// run\n\npackage main\n\nfunc main() {\n\tundefinedThing() // ERROR \"undefined: undefinedThing\"\n}\n";
    let errs = wanted_errors(src, "x.go").expect("应能解析");
    assert_eq!(errs.len(), 1);
    assert_eq!(errs[0].line_num, 6, "前缀行号应是 ERROR 注释所在行");
    assert_eq!(errs[0].re_str, "undefined: undefinedThing");
}

#[test]
fn r4_一行多个引号_产生多条期望() {
    // :1465 —— 每一对引号都是一条独立期望（mainsig.go 的第 10 行就是 2 条）
    let src = "package main\nfunc main(int) {}\nfunc main() int { return 1 } // ERROR \"func main must have no arguments and no return values\" \"main redeclared in this block\"\n";
    let errs = wanted_errors(src, "mainsig.go").expect("应能解析");
    assert_eq!(errs.len(), 2, "同行两条期望");
    assert_eq!(errs[0].line_num, 3);
    assert_eq!(errs[1].line_num, 3, "两条在同一行");
    assert!(errs[1].re_str.contains("main redeclared"));
}

#[test]
fn r4_支持_gc_error_与_autogenerated() {
    // :1433-1434 —— // GC_ERROR 与 // GC_ERRORAUTO
    let src = "package main\nfunc main() { panic(\"x\") } // GC_ERROR \"unreachable\"\n";
    let errs = wanted_errors(src, "x.go").expect("应能解析");
    assert_eq!(errs.len(), 1);
    assert!(!errs[0].auto, "GC_ERROR 不是 auto");

    let src2 = "package main\nfunc main() { m() } // GC_ERRORAUTO \"inlining call\"\n";
    let errs2 = wanted_errors(src2, "x.go").expect("应能解析");
    assert_eq!(errs2.len(), 1);
    assert!(
        errs2[0].auto,
        "ERRORAUTO 应标 auto（匹配时不过滤 <autogenerated>）"
    );
}

#[test]
fn r4_四斜杠_禁用该行的_error() {
    // :1446-1449 —— 含 "////" 的行跳过
    let src = "package main\nfunc main() {\n\tbad() ////// ERROR \"this one is disabled\"\n}\n";
    let errs = wanted_errors(src, "x.go").expect("应能解析");
    assert!(
        errs.is_empty(),
        "//// 应禁用该行的 ERROR 期望，实际 {:?}",
        errs
    );
}

#[test]
fn r4_line_占位符_折算成绝对行号() {
    // :1466-1476 —— LINE / LINE+n / LINE-n 替换为 <short>:<绝对行号>
    let src = "package main\nfunc main() {\n\t_ = 1\n\t_ = 2 // ERROR \"LINE:[^\\n]*\" LINE:3 \"LINE+1:[^\\n]*\"\n}\n";
    let errs = wanted_errors(src, "x.go").expect("应能解析");
    assert_eq!(errs.len(), 2, "两条期望");
    // ERROR 注释在第 4 行（package main / func main() { / _ = 1 / _ = 2 // ERROR）
    assert_eq!(errs[0].re_str, "x.go:4:[^\\n]*", "裸 LINE 指向本行");
    assert_eq!(errs[1].re_str, "x.go:5:[^\\n]*", "LINE+1 指向下一行");
}

#[test]
fn r4_普通注释不产生期望() {
    let src = "package main\nfunc main() {}\n// 这只是注释，不是 ERROR\n";
    assert!(wanted_errors(src, "x.go").expect("应能解析").is_empty());
}

// ══ errorCheck 匹配算法（`:1249-1304`）════════════════════════════════════

fn diag(line: u32, msg: &str) -> String {
    format!("x.go:{line}:1: {msg}")
}

#[test]
fn errorcheck_按前缀取诊断_并砍掉位置前缀() {
    // :1254 取走该前缀的全部诊断；:1265-1268 砍掉第一个空格之前的部分
    let want = wanted_errors(
        "package main\nfunc main() {\n\tm() // ERROR \"undefined: m\"\n}\n",
        "x.go",
    )
    .unwrap();
    let out = format!("{}\n", diag(3, "undefined: m"));
    assert!(
        error_check(&out, &want).is_ok(),
        "应当匹配上：{:?}",
        error_check(&out, &want)
    );
}

#[test]
fn errorcheck_未锚定匹配_不要求整条相等() {
    let want = wanted_errors(
        "package main\nfunc main() {\n\tm() // ERROR \"undefined\"\n}\n",
        "x.go",
    )
    .unwrap();
    // 关键字出现在消息**中间** —— 官方是 regexp.MatchString（**不锚定**），
    // 所以前后有别的内容也能命中
    let out = format!("\n{}", diag(3, "m (type int) is undefined in this scope"));
    assert!(error_check(&out, &want).is_ok(), "未锚定：含关键字即可命中");
}

#[test]
fn errorcheck_池子里有剩_算失败() {
    let want = wanted_errors(
        "package main\nfunc main() {\n\tm() // ERROR \"undefined: m\"\n}\n",
        "x.go",
    )
    .unwrap();
    let out = format!(
        "{}\n{}\n",
        diag(3, "undefined: m"),
        diag(9, "凭空多出来的诊断")
    );
    let errs = error_check(&out, &want).unwrap_err();
    assert!(
        errs.iter().any(|e| e.contains("Unmatched")),
        "未被期望覆盖的诊断应报 Unmatched Errors，实际：{errs:?}"
    );
}

#[test]
fn errorcheck_同前缀的多余诊断_判失败() {
    // ⚠️ 官方**不允许**忽略没被任何期望命中的诊断：没命中的会**放回池子**（`:1272`），
    // 最后池子非空 ⇒ `Unmatched Errors`（`:1281-1304`）。
    // 我最初把这里写反了（以为「同前缀的多余诊断可以忽略」）—— 那样会漏判真失败。
    let want = wanted_errors(
        "package main\nfunc f() {\n\tm() // ERROR \"undefined: m\"\n}\n",
        "x.go",
    )
    .unwrap();
    let out = format!(
        "{}\n{}\n",
        diag(3, "undefined: m"),
        diag(3, "missing return")
    );
    let errs = error_check(&out, &want).unwrap_err();
    assert!(
        errs.iter().any(|e| e.contains("Unmatched")),
        "同前缀却没被命中的诊断必须算失败，实际：{errs:?}"
    );
}

#[test]
fn errorcheck_一个期望_覆盖同一行两条诊断() {
    // T-C-19 typecheck.go 实测是 5 条诊断配 4 条期望 —— 能过的原因是
    // **每条诊断都被某条期望命中**（不是「允许剩一条」）。这里用交替模式复现。
    let want = wanted_errors(
        "package main\nfunc f() {\n\tm() // ERROR \"undefined: m|missing return\"\n}\n",
        "x.go",
    )
    .unwrap();
    let out = format!(
        "{}\n{}\n",
        diag(3, "undefined: m"),
        diag(3, "missing return")
    );
    let r = error_check(&out, &want);
    assert!(r.is_ok(), "交替模式应当同时覆盖两条诊断（{:?}）", r.err());
}

#[test]
fn errorcheck_缺诊断_报_missing() {
    let want = wanted_errors(
        "package main\nfunc main() {\n\tm() // ERROR \"undefined: m\"\n}\n",
        "x.go",
    )
    .unwrap();
    let errs = error_check("", &want).unwrap_err();
    assert!(
        errs.iter().any(|e| e.contains("missing error")),
        "期望有诊断却没有，应报 missing，实际：{errs:?}"
    );
}

#[test]
fn replace_prefix_逐条替换_含续行() {
    // :2059-2072 —— 行首、行中、\n 之后、\n\t 之后都要换
    let s = "/work/go_source_code/test/x.go:1:1: a\n\t/work/go_source_code/test/x.go:2:1: b";
    let got = replace_prefix(s, "/work/go_source_code/test/x.go", "x.go");
    assert!(!got.contains("/work/"), "所有位置的路径都该被换掉：{got}");
    assert_eq!(got, "x.go:1:1: a\n\tx.go:2:1: b");
}

// ══ 正则子集：够用即止，但**不认识就报错**══════════════════════════════════

#[test]
fn matcher_子集内的构造() {
    // 字面量
    assert!(
        unanchored_match(
            "too many arguments",
            "invalid operation: too many arguments for f"
        )
        .unwrap()
    );
    // 交替
    assert!(unanchored_match("compos|conver", "composite literal uses unkeyed fields").unwrap());
    assert!(unanchored_match("conver|incompatible|cannot", "incompatible types").unwrap());
    // .* 跨行（官方用 .* 跨多行匹配续拼的诊断）
    assert!(
        unanchored_match(
            "a refers to b\n.*b refers to c",
            "a refers to b\n\tpkg.go:9: b refers to c"
        )
        .unwrap()
    );
    // 转义：\. 匹配字面点
    assert!(
        unanchored_match(
            r"undefined.*runtime\.init",
            "undefined: runtime.init (type name too long)"
        )
        .unwrap()
    );
    // 转义：\\ 匹配字面反斜杠
    assert!(unanchored_match(r"a\\b", r"path\to\a\b").unwrap());
    // 不匹配时返回 Ok(false)，不是 Err
    assert!(!unanchored_match("undefined", "all good").unwrap());
}

#[test]
fn matcher_不支持的构造_明确报错() {
    // 语料里有 5435 条模式用到 {n,m} [ ] ( ) + ? ^ $ ——
    // 本实现**不认识**它们时必须报错，绝不能静默当成「不匹配」，
    // 否则那 5435 条里的多数会被误判成「编译器有 bug」。
    for bad in [
        "a+b",    // +
        "ab?c",   // ?
        "[abc]",  // 字符类
        "(ab)c",  // 分组
        "a{2,3}", // 计数
        "^abc",   // 行首锚
        "abc$",   // 行尾锚
    ] {
        let r = unanchored_match(bad, "abc");
        assert!(
            r.is_err(),
            "不支持的构造 {bad:?} 应当报错，而不是静默返回不匹配（实际 {:?}）",
            r
        );
    }
}

#[test]
fn matcher_空模式匹配一切() {
    // 正则语义：空模式匹配任意字符串
    assert!(unanchored_match("", "anything").unwrap());
}
