//! 比较器与诊断切分（R2 / R3 / R4）。
//!
//! 规则逐条来自 `go_source_code/src/cmd/internal/testdir/testdir_test.go`：
//! - [`check_expected_output`] —— `checkExpectedOutput`（`:1172-1193`）
//! - [`split_output`] —— `splitOutput`（`:1195-1213`）
//! - [`wanted_errors`] —— `wantedErrors`（`:1440-1499`）
//! - [`error_check`] —— `errorCheck` 的匹配算法（`:1249-1304`）
//! - [`replace_prefix`] —— `replacePrefix`（`:2059-2072`）
//!
//! # 正则的范围（**必读**）
//!
//! 顶层 `test/` 的 ERROR 模式共 **5435 条**，用到了 `{n,m}` / `[...]` / `+` / `?` / `^` / `$`
//! 等全套 Go 正则。自己实现一套正则引擎不现实（那是另一个项目，而且错得很安静）。
//! 而 **E4 冻结的 20 个样本只需要「字面量 + `|` + `.` / `.*` + `\` 转义」** 这个子集。
//!
//! 所以本模块实现该子集；遇到子集外的构造，[`unanchored_match`] **返回错误**，
//! 由上层判 `harness-failure`。
//! **绝不静默当成「不匹配」** —— 那会把 5435 条里的多数用例误判成「编译器有 bug」。
//! 这是本模块最重要的一条设计约束。

use std::fmt;

// ══ 错误类型 ═══════════════════════════════════════════════════════════════

/// 比较阶段的失败。
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CompareError {
    /// 模式里有本实现不认识的正则构造（见模块头的「正则的范围」）
    UnsupportedRegex {
        /// 出问题的模式
        pattern: String,
        /// 命中的构造名
        construct: String,
    },
    /// `// ERROR` 行里一个引号模式都没有（官方 `:1463` 直接 Fatalf）
    InvalidErrCheckLine {
        /// 行号
        line_num: u32,
        /// 原文
        text: String,
    },
}

impl fmt::Display for CompareError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnsupportedRegex { pattern, construct } => write!(
                f,
                "harness 不支持这个正则构造 {construct:?}：{pattern:?}（M0 只实现字面量 / | / . / .* / 反斜杠转义；\
                 其余构造请在 Phase 2 结束前决定是扩展实现还是引入 regex crate）"
            ),
            Self::InvalidErrCheckLine { line_num, text } => {
                write!(f, "第 {line_num} 行的 ERROR 注释里没有引号模式：{text}")
            }
        }
    }
}

impl std::error::Error for CompareError {}

// ══ R2：输出期望（`:1172-1193`）═════════════════════════════════════════════

/// 输出不匹配。
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OutputMismatch {
    /// 归一后实际看到的
    pub got: String,
    /// `.out` 的期望内容；`None` 表示该文件不存在
    pub want: Option<String>,
}

impl fmt::Display for OutputMismatch {
    /// **两种措辞必须能区分**（官方 `:1186-1190`）：
    /// 有 `.out` 说「内容不符」，无 `.out` 说「本应为空却非空」——
    /// 这决定了人该去查输出还是去查「为什么它不安静」。
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.want {
            Some(want) => write!(
                f,
                "输出与 .out 期望不匹配。\n期望：{want:?}\n实际：{:?}",
                self.got
            ),
            None => write!(
                f,
                "缺少 .out 期望文件时，输出本应为空，却看到：{:?}",
                self.got
            ),
        }
    }
}

/// 比对输出与期望（`checkExpectedOutput`，`:1172-1193`）。
///
/// `out_file` 是 `.out` 的**内容**（由调用方按 R2 的口径从 **goroot 的 test 目录**读出来；
/// 「期望文件在 goroot 下而不是测试文件所在目录」这条是路径解析的事，不属于本函数）。
/// `None` 表示该文件不存在 —— 此时**期望为空**（不是「任意输出都通过」）。
///
/// 比较前把 `\r\n` 归一为 `\n`（`:1184`），然后**严格相等**（`:1185`，不加锚、不忽略空白）。
pub fn check_expected_output(got: &str, out_file: Option<&str>) -> Result<(), OutputMismatch> {
    let got = got.replace("\r\n", "\n");
    let want = out_file.map(str::to_string);
    if got == want.clone().unwrap_or_default() {
        return Ok(());
    }
    Err(OutputMismatch { got, want })
}

// ══ R3：诊断切分（`:1195-1213`）═════════════════════════════════════════════

/// 把编译器输出切成一条条诊断（`splitOutput`）。
///
/// - 以 `\t` 开头的行是**上一条的续行**，拼进上一条；
/// - 以 `go tool` / `#` 开头的行跳过；`<autogenerated>` 开头的行
///   在 `want_auto` 为**假**时跳过（官方 `:1206`：这些行无法匹配）；
/// - 其余非空行各自成条。
///
/// 与官方的一处**刻意偏差**：官方 `res[len(res)-1] += …` 在 `res` 为空且首行是 `\t` 时会 panic；
/// 这里跳过这种行（`:1204` 的语义在真实输出里不会出现，防御性处理更稳）。
pub fn split_output(out: &str, want_auto: bool) -> Vec<String> {
    let mut res: Vec<String> = Vec::new();
    for raw in out.split('\n') {
        let line = raw.strip_suffix('\r').unwrap_or(raw); // :1201-1202
        if let Some(rest) = line.strip_prefix('\t') {
            if let Some(last) = res.last_mut() {
                last.push('\n');
                last.push_str(rest);
            }
        } else if line.starts_with("go tool")
            || line.starts_with('#')
            || (!want_auto && line.starts_with("<autogenerated>"))
        {
            // 丢弃（:1206）
        } else if !line.trim().is_empty() {
            res.push(line.to_string()); // :1208-1209
        }
    }
    res
}

// ══ replacePrefix（`:2059-2072`）════════════════════════════════════════════

/// 把诊断里的**全路径**换成**短文件名**（官方的 `replacePrefix`）。
///
/// 官方换四种位置：行首、行中（空格后）、换行后、**换行 + 制表符后**
/// —— 最后一种是**续行里的路径**，漏了它就匹配不上（官方 `:2067` 专门处理）。
pub fn replace_prefix(s: &str, old: &str, new: &str) -> String {
    if !s.contains(old) {
        return s.to_string();
    }
    let mut out = s.replace(&format!(" {old}"), &format!(" {new}"));
    out = out.replace(&format!("\n{old}"), &format!("\n{new}"));
    out = out.replace(&format!("\n\t{old}"), &format!("\n\t{new}"));
    if let Some(rest) = out.strip_prefix(old) {
        out = format!("{new}{rest}");
    }
    out
}

// ══ R4：ERROR 注释解析（`:1440-1499`）══════════════════════════════════════

/// 一条期望错误。
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WantedError {
    /// 折算后的模式（`LINE±n` 已换成 `<短名>:<行号>`）
    pub re_str: String,
    /// `// ERROR` 注释所在的行号
    pub line_num: u32,
    /// 短文件名
    pub file: String,
    /// 是否来自 `ERRORAUTO` / `GC_ERRORAUTO`（匹配时不过滤 `<autogenerated>`）
    pub auto: bool,
}

impl WantedError {
    /// 匹配时用来取诊断的前缀（官方 `:1486`）
    fn prefix(&self) -> String {
        if self.auto {
            "<autogenerated>".to_string()
        } else {
            format!("{}:{}", self.file, self.line_num)
        }
    }
}

/// 解析源码里的 `// ERROR` / `// GC_ERROR` / `// ERRORAUTO` / `// GC_ERRORAUTO` 注释。
///
/// 官方要点（逐条）：
/// - 含 `////` 的行**禁用**该行的 ERROR（`:1446-1449`）
/// - **一行可以有多对引号**，每一对都是一条独立期望（`:1461-1465`）
/// - `LINE` / `LINE+n` / `LINE-n` 折算成 `<短名>:<绝对行号>`（`:1466-1476`）
/// - 一个引号都没有 ⇒ 官方直接 Fatalf（`:1463`），这里返回 Err
pub fn wanted_errors(src: &str, short: &str) -> Result<Vec<WantedError>, CompareError> {
    let mut out = Vec::new();
    for (i, line) in src.split('\n').enumerate() {
        let line_num = (i + 1) as u32;
        // :1446-1449 双注释即禁用
        if line.contains("////") {
            continue;
        }
        let Some((auto, rest)) = parse_err_comment(line) else {
            continue;
        };
        let patterns = quoted_patterns(rest);
        if patterns.is_empty() {
            return Err(CompareError::InvalidErrCheckLine {
                line_num,
                text: line.to_string(),
            });
        }
        for p in patterns {
            out.push(WantedError {
                re_str: substitute_line(&p, short, line_num),
                line_num,
                file: short.to_string(),
                auto,
            });
        }
    }
    Ok(out)
}

/// 找出 ERROR 类注释并返回 `(是否 auto, 注释之后的部分)`。
///
/// 对应官方两个正则：`// (?:GC_)?ERRORAUTO (.*)` 与 `// (?:GC_)?ERROR (.*)`。
/// 注意 `// GC_ERRORAUTO ` **不会**被后者匹配（`ERROR` 后面要求是空格，而这里是 `A`），
/// 所以两种前缀可以分开查找。
fn parse_err_comment(line: &str) -> Option<(bool, &str)> {
    for (pat, auto) in [
        ("// GC_ERRORAUTO ", true),
        ("// ERRORAUTO ", true),
        ("// GC_ERROR ", false),
        ("// ERROR ", false),
    ] {
        if let Some(i) = line.find(pat) {
            return Some((auto, &line[i + pat.len()..]));
        }
    }
    None
}

/// 取引号里的模式（官方 `errQuotesRx = "([^"]*)"`，取**所有**非空匹配）。
fn quoted_patterns(rest: &str) -> Vec<String> {
    let mut out = Vec::new();
    let chars = rest.chars();
    let mut cur = String::new();
    let mut in_quote = false;
    for c in chars {
        if in_quote {
            if c == '"' {
                in_quote = false;
                if !cur.is_empty() {
                    out.push(std::mem::take(&mut cur));
                } else {
                    cur.clear();
                }
            } else {
                cur.push(c);
            }
        } else if c == '"' {
            in_quote = true;
            cur.clear();
        }
    }
    out
}

/// 把模式里的 `LINE` / `LINE+n` / `LINE-n` 折算成 `<短名>:<行号>`。
///
/// 官方用 `lineRx = LINE(([+-])(\d+))?`（`:1436`）逐个替换。注意 `LINE+12` 这种
/// **多位**偏移也要对（官方 `m[5:]` 之后 `Atoi`）。
fn substitute_line(pattern: &str, short: &str, line_num: u32) -> String {
    const KEY: &str = "LINE";
    let mut out = String::new();
    let mut rest = pattern;
    while let Some(i) = rest.find(KEY) {
        out.push_str(&rest[..i]);
        let after = &rest[i + KEY.len()..];
        // 只在后面紧跟可选的 (+|-)数字 时才替换，其余 `LINE` 原样保留
        let (delta, tail) = if after.starts_with('+') || after.starts_with('-') {
            let sign = if after.starts_with('-') { -1i64 } else { 1 };
            let digits: String = after[1..]
                .chars()
                .take_while(char::is_ascii_digit)
                .collect();
            if digits.is_empty() {
                (0, after)
            } else {
                let n: i64 = digits.parse().unwrap_or(0);
                (sign * n, &after[1 + digits.len()..])
            }
        } else {
            (0, after)
        };
        let target = (line_num as i64 + delta).max(0) as u32;
        out.push_str(&format!("{short}:{target}"));
        rest = tail;
    }
    out.push_str(rest);
    out
}

// ══ errorCheck 匹配算法（`:1249-1304`）═════════════════════════════════════

/// 按期望逐条匹配诊断（`errorCheck` 的核心，`:1249-1304`）。
///
/// 官方语义，逐条照搬：
/// 1. 按 `<短名>:<行号>` 前缀**取走**该行的全部诊断（`partitionStrings`）；
/// 2. 逐条**砍掉第一个空格之前的内容**（丢掉 `file:line:col:`，避免误匹配文件名，`:1265-1268`）；
/// 3. **未锚定**正则匹配：命中则算这条期望满足；
/// 4. **没命中的放回池子** —— 它可能被别的期望复用（`:1272`）；
/// 5. 池子里剩下的（且属于本文件的）⇒ `Unmatched Errors`（`:1281-1304`）。
///
/// `want_auto` 取自「是否有 `ERRORAUTO` 期望」—— 官方那里是 action 级开关（`errorcheckwithauto`），
/// M0 的 v0 模式不涉及，用期望级的 `auto` 推导等价且更贴近 R4 的本意。
///
/// **不支持的正则构造**会被标成 `UNSUPPORTED-REGEX:` 前缀返回，**不混进 mismatch** ——
/// 上层据此判 `harness-failure` 而不是「编译器有 bug」。
pub fn error_check(out: &str, want: &[WantedError]) -> Result<(), Vec<String>> {
    let want_auto = want.iter().any(|w| w.auto);
    let mut pool = split_output(out, want_auto);
    let mut errs: Vec<String> = Vec::new();
    let local = want.first().map(|w| w.file.clone()).unwrap_or_default();

    for w in want {
        let prefix = w.prefix();
        let (mut taken, rest) = partition(&prefix, &pool);
        pool = rest;
        if taken.is_empty() {
            errs.push(format!(
                "missing error {:?} @ {}:{}",
                w.re_str, w.file, w.line_num
            ));
            continue;
        }
        let mut matched = false;
        for msg in taken.drain(..) {
            // 砍掉第一个空格之前的部分（file:line:col:）
            let text = match msg.split_once(' ') {
                Some((_, t)) => t,
                None => msg.as_str(),
            };
            match unanchored_match(&w.re_str, text) {
                Ok(true) => matched = true,
                Ok(false) => pool.push(msg), // 放回池子（:1272）
                Err(e) => errs.push(format!("UNSUPPORTED-REGEX: {e}")),
            }
        }
        if !matched && !errs.iter().any(|e| e.starts_with("UNSUPPORTED-REGEX")) {
            errs.push(format!(
                "no match for {:?} @ {}:{}",
                w.re_str, w.file, w.line_num
            ));
        }
    }

    // 只把**本文件**的剩余诊断算作 Unmatched（官方 :1285-1296 过滤掉别的包的）
    let leftovers: Vec<String> = pool
        .into_iter()
        .filter(|l| file_part(l).rsplit('/').next() == Some(local.as_str()))
        .collect();
    if !leftovers.is_empty() {
        errs.push(format!("Unmatched Errors: {}", leftovers.join(" | ")));
    }
    if errs.is_empty() { Ok(()) } else { Err(errs) }
}

/// 取走（或留下）所有以 `prefix` 开头的行。
fn partition(prefix: &str, lines: &[String]) -> (Vec<String>, Vec<String>) {
    let mut hit = Vec::new();
    let mut rest = Vec::new();
    for l in lines {
        if l.starts_with(prefix) {
            hit.push(l.clone());
        } else {
            rest.push(l.clone());
        }
    }
    (hit, rest)
}

/// 取诊断的「文件部分」（第一个冒号之前）。
fn file_part(line: &str) -> &str {
    line.split_once(':').map_or(line, |(f, _)| f)
}

// ══ 正则子集匹配器 ══════════════════════════════════════════════════════════

/// **未锚定**匹配（官方用 `regexp.MatchString`，**不加** `^`/`$`）。
///
/// 支持：字面量、`.`（任意单字符）、`.*`（任意序列）、`|`（交替）、`\` 转义。
/// 遇到**不支持**的构造（`+` `?` `[` `(` `{` `^` `$`）⇒ 返回
/// [`CompareError::UnsupportedRegex`]，**绝不静默返回 false**。
pub fn unanchored_match(pattern: &str, text: &str) -> Result<bool, CompareError> {
    let alts = split_alternatives(pattern)?;
    Ok(alts.iter().any(|alt| match_seq(alt, text)))
}

/// 模式里的一个片段：字面文本，或「任意长度」通配。
#[derive(Debug, Clone, PartialEq, Eq)]
enum Item {
    Lit(String),
    AnySeq,
}

/// 按**未被转义**的 `|` 切分交替分支。
///
/// 用**索引**循环而不是 `while let Some(c) = it.next()`：后者在循环体内还要
/// `it.peek()` / `it.next()`（处理 `.*` 与 `\x` 转义），`by_ref()` 适配器会与之冲突。
fn split_alternatives(pattern: &str) -> Result<Vec<Vec<Item>>, CompareError> {
    let chars: Vec<char> = pattern.chars().collect();
    let mut alts: Vec<Vec<Item>> = Vec::new();
    let mut cur: Vec<Item> = Vec::new();
    let mut lit = String::new();
    let mut i = 0;
    let unsupported = |c: char| CompareError::UnsupportedRegex {
        pattern: pattern.to_string(),
        construct: c.to_string(),
    };
    while i < chars.len() {
        let c = chars[i];
        i += 1;
        match c {
            '|' => {
                if !lit.is_empty() {
                    cur.push(Item::Lit(std::mem::take(&mut lit)));
                }
                alts.push(std::mem::take(&mut cur));
            }
            '.' => {
                // `.` 后面紧跟 `*` ⇒ 任意长度；单独一个 `.` ⇒ 任意单字符
                if chars.get(i) == Some(&'*') {
                    i += 1;
                    if !lit.is_empty() {
                        cur.push(Item::Lit(std::mem::take(&mut lit)));
                    }
                    cur.push(Item::AnySeq);
                } else {
                    // 用一个不会出现在文本里的标记表示「任意单字符」
                    lit.push('\u{0}');
                }
            }
            '\\' => match chars.get(i) {
                Some(&escaped) => {
                    i += 1;
                    // ⚠️ **`\` 后的字符分两类，不能一律当字面量**（T38 实测踩过）：
                    //
                    // ① **转义控制字符**（`\n` `\t` `\r` `\f` `\v` `\a`）⇒ 真正的控制符。
                    //    Go 的 `regexp/syntax` 把它们当 Perl 类转义（`perl.go` 的 `escape` 表），
                    //    所以 `\n` 匹配的是**换行符**，不是字母 `n`。
                    //    早先一律 `lit.push(escaped)` ⇒ `\n` 变成字面 `n`，
                    //    于是 T-C-13 `initloop.go` 的跨行期望
                    //    （`a refers to b\n.*b refers to c\n.*c refers to a`）永远匹配不上
                    //    续接后的诊断 —— 判 `compiler-failure`，而编译器其实完全正确。
                    //
                    // ② **转义元字符**（`\.` `\*` `\|` `\\` `\+` …）⇒ 字面该字符。
                    //    这类必须保持字面语义：若把 `\.` 解释成「任意字符」，
                    //    判定就被**放宽**了（`a\.b` 会匹配 `axb`）—— 那比误判更危险。
                    //
                    // 分类之外的 `\x`（如 `\d` `\w`）属于**不支持** ⇒ 已在下面报错。
                    match escaped {
                        'n' => lit.push('\n'),
                        't' => lit.push('\t'),
                        'r' => lit.push('\r'),
                        'f' => lit.push('\u{c}'),
                        'v' => lit.push('\u{b}'),
                        'a' => lit.push('\u{7}'),
                        // 其余一律字面（含 `\\` `\.` `\|` 等元字符转义）
                        other => lit.push(other),
                    }
                }
                None => return Err(unsupported('\\')),
            },
            // 明确不支持的构造 —— 报错而不是静默
            '+' | '?' | '[' | ']' | '(' | ')' | '{' | '}' | '^' | '$' => {
                return Err(unsupported(c));
            }
            _ => lit.push(c),
        }
    }
    if !lit.is_empty() {
        cur.push(Item::Lit(lit));
    }
    alts.push(cur);
    Ok(alts)
}

/// 在 `text` 里**任意位置**匹配 `items` 序列。
fn match_seq(items: &[Item], text: &str) -> bool {
    if items.is_empty() {
        return true; // 空模式匹配一切（正则语义）
    }
    let bytes: Vec<char> = text.chars().collect();
    // 起点穷举（未锚定）
    for start in 0..=bytes.len() {
        if match_from(items, &bytes, start) {
            return true;
        }
    }
    false
}

fn match_from(items: &[Item], text: &[char], pos: usize) -> bool {
    let Some(first) = items.first() else {
        return true;
    };
    match first {
        Item::AnySeq => {
            // 任意长度：尝试所有结束位置
            for end in pos..=text.len() {
                if match_from(&items[1..], text, end) {
                    return true;
                }
            }
            false
        }
        Item::Lit(lit) => {
            let chars: Vec<char> = lit.chars().collect();
            if chars.contains(&'\u{0}') {
                // 含「任意单字符」标记：逐位比对，遇标记吃一个字符
                for at in pos..=text.len() {
                    if match_lit_at(&chars, 0, text, at) {
                        return true;
                    }
                }
                false
            } else if text[pos..].starts_with(&chars[..]) {
                match_from(&items[1..], text, pos + chars.len())
            } else {
                false
            }
        }
    }
}

/// 带「任意单字符」标记的字面量在 `start` 处能否匹配。
fn match_lit_at(lit: &[char], li: usize, text: &[char], start: usize) -> bool {
    if li == lit.len() {
        return match_from_remaining(lit, li, text, start);
    }
    if lit[li] == '\u{0}' {
        if start < text.len() && match_lit_at(lit, li + 1, text, start + 1) {
            return true;
        }
        // 标记也允许匹配空（尽量宽松，与 `.` 至少吃一个字符的语义略有差别）
        return match_lit_at(lit, li + 1, text, start);
    }
    if start < text.len() && text[start] == lit[li] {
        return match_lit_at(lit, li + 1, text, start + 1);
    }
    false
}

fn match_from_remaining(_lit: &[char], _li: usize, _text: &[char], _start: usize) -> bool {
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn line_折算_覆盖_多位偏移() {
        assert_eq!(substitute_line("LINE:x", "f.go", 5), "f.go:5:x");
        assert_eq!(substitute_line("LINE+12:x", "f.go", 5), "f.go:17:x");
        assert_eq!(substitute_line("LINE-2:x", "f.go", 5), "f.go:3:x");
        // 官方正则是 `LINE(([+-])(\d+))?` —— 符号后**没有数字**时只匹配 `LINE`，
        // 那个 `+` 作为普通文本留下（我最初以为整段不动，是错的）
        assert_eq!(substitute_line("LINE+:x", "f.go", 5), "f.go:5+:x");
        // ⚠️ 官方的 LINE 替换是**无锚点子串替换**（正则没有 \\b 边界），
        // 所以注释里出现的普通单词 LINE 也会被改写 —— 这是官方行为，照搬。
        assert_eq!(substitute_line("no LINE here", "f.go", 5), "no f.go:5 here");
        // 完全不含 LINE 的原样返回
        assert_eq!(substitute_line("abc", "f.go", 5), "abc");
    }

    #[test]
    fn 引号模式_取所有非空匹配() {
        assert_eq!(quoted_patterns(r#""a" "b""#), vec!["a", "b"]);
        assert_eq!(quoted_patterns(r#" "x" trailing "#), vec!["x"]);
        assert!(quoted_patterns("no quotes here").is_empty());
    }

    #[test]
    fn error_注释_不吃_gc_errorauto() {
        assert_eq!(
            parse_err_comment("// GC_ERRORAUTO \"x\""),
            Some((true, "\"x\""))
        );
        assert_eq!(
            parse_err_comment("// GC_ERROR \"x\""),
            Some((false, "\"x\""))
        );
    }

    #[test]
    fn 诊断_只算本文件的剩余() {
        assert_eq!(file_part("x.go:3:1: msg"), "x.go");
        assert_eq!(file_part("/a/b/x.go:3:1: msg"), "/a/b/x.go");
    }
}
